update dotfiles Mon 21 Apr 2025 05:21:24 WAT

diff --git a/scripts/savechanges b/scripts/savechanges
--- a/scripts/savechanges
+++ b/scripts/savechanges
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
 
-commitdot
-notes push
+commitdot || echo -e "\e[31m \n commit failed..\n check network connection \e[37m"
+notes push || echo -e "\e[31m \n commit failed..\n check network connection \e[37m"
+if [[ $0 == 0 ]]; then
+echo -e "\e[32 success! \e[37m"
+fi
+
+
+
+
